repositories:
  - name: llm-d-infra
    url: https://llm-d-incubation.github.io/llm-d-infra/

  - name: llm-d-modelservice
    url: https://llm-d-incubation.github.io/llm-d-modelservice/

releases:
  - name: infra
    chart: llm-d-infra/llm-d-infra
    version: v1.4.0
    values:
      - infra/values.yaml

  - name: gaie-llama
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v1.4.0
    needs:
      - infra
    values:
      - gaie/llama-values.yaml

  - name: ms-llama
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.4.9
    needs:
      - gaie-llama
    values:
      - models/llama-3-8b/values.yaml

  - name: gaie-phi-4
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v1.4.0
    needs:
      - infra
    values:
      - gaie/phi-4-values.yaml

  - name: ms-phi-4
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.4.9
    needs:
      - gaie-phi-4
    values:
      - models/phi4/values.yaml

  - name: gaie-qwen3
    chart: oci://registry.k8s.io/gateway-api-inference-extension/charts/inferencepool
    version: v1.4.0
    needs:
      - infra
    values:
      - gaie/qwen3-8b-values.yaml

  - name: ms-qwen3
    chart: llm-d-modelservice/llm-d-modelservice
    version: v0.4.9
    needs:
      - gaie-qwen3
    values:
      - models/qwen/values.yaml