modelArtifacts:
  name: "Qwen/Qwen3-0.6B"
  uri: "hf://Qwen/Qwen3-0.6B"
  authSecretName: "llm-d-hf-token"

  labels:
    app: vllm-llama-3-8b
    llm-d.ai/inference-serving: "true"

  size: 5Gi

decode:
  replicas: 1

  parallelism:
    tensor: 1

  nodeSelector:
    node-role.kubernetes.io/gpu-worker: ""

  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

  containers:
    - name: vllm
      image: "vllm/vllm-openai:latest"
      modelCommand: vllmServe
      mountModelVolume: true
      args:
        - "--served-model-name"
        - "Qwen/Qwen3-0.6B"
        - "--max-model-len"
        - "4096"
      env:
        - name: VLLM_CACHE_ROOT
          value: /tmp/vllm
        - name: HOME
          value: /tmp

prefill:
  replicas: 0

routing:
  proxy:
    enabled: false